#!/bin/bash

HOST=$1
SSL_PORT=$2
KEY_LEN_LIMIT=$3
VULN_SUIT_LIST=$4
echo -e "[*] assessing host \e[3;36m $HOST:$SSL_PORT\e[0m"
for ciper in `sslyze --regular $HOST:$SSL_PORT | awk -F\ '/[0-9]*
  bits/ { print $1"_"$2"_"$3 }'`
